### DISCUSSION TITLE
Climate object configuration for HomeAssistant

### DISCUSSION THREAD

**Discussion by cristimi** [jshank/bwalink#27] [Ideas]
I just want to share my configuration to get the SPA as a climate object in HomeAssistant, hopefully it is useful for somebody else. I have been using it for a while now and it is working well.

```
mqtt:
  climate:
    - name: "Drop SPA MQTT"
      unique_id: drop_spa_mqtt
      precision: 0.5
      min_temp: 10
      max_temp: 40
      temp_step: 0.5
      modes:
        - 'off'   # rest, ready_in_rest
        - auto  # ready 
      preset_modes:
        - "low"
        - "high"
      preset_mode_state_topic: "homie/bwa/spa/temperature-range"
      preset_mode_command_topic: "homie/bwa/spa/temperature-range/set"
      mode_state_topic: "homie/bwa/spa/heating-mode"
      mode_state_template: >-
        {% set values = { 'ready':'auto', 'rest':'off', 'ready_in_rest':'off'} %}
        {{ values[value] if value in values.keys() else 'off' }}
      mode_command_topic: "homie/bwa/spa/heating-mode/set"
      mode_command_template: >-
        {% set values = { 'heat':'ready', 'off':'rest'} %}
        {{ values[value] if value in values.keys() else 'rest' }}
      current_temperature_topic: "homie/bwa/spa/current-temperature"
      temperature_state_topic: "homie/bwa/spa/target-temperature"
      temperature_command_topic: "homie/bwa/spa/target-temperature/set"
```

Also I was wondering if it is possible somehow to expose some parameters from ELFIN, like IP Adress and RSSI. I have been struggling to have a stable wifi connection and having those exposed would help troubleshooting.
